---
  - hosts: all
    become: yes
    pre_tasks:
      - name: Create user
        user:
          name: "{{ user_name }}"
          password: "{{ user_pass | password_hash('sha512') }}"
          groups: sudo
          shell: /bin/bash
      - replace:
          path: /etc/network/interfaces
          regexp: 'ens33'
          replace: 'ens32'
      - lineinfile:
          path: /var/run/network/ifstate
          line: 'ens32=ens32'
          state: present
        
    roles:
      - { role: /home/nvermand/Scripts/ansible/roles/common}

    
